version: "3"

tasks:
  generate:
    cmds:
      - /bin/bash -c "pushd .component_generator; ./generate_overwrite.sh; popd"
      - go generate ./...
      - git add wire_gen.go
  check:
    cmds:
      - trunk check --sample 10
  pre-commit:
    cmds:
      - task: generate
      - task: gosums
      - task: check
  tidy:
    desc: Run "go mod tidy -go=1.8" in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go mod tidy -go=1.18; popd' '_' {} \;
  update:
    desc: Run "go get -u ./..." in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go get -u ./...; popd' '_' {} \;
  test:
    desc: Run "go test ./..." in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go test ./...; popd' '_' {} \;
  workuse:
    desc: Add all plugins to go.work
    cmds:
      - go work init . || exit 0
      - go work use $(find . -name 'go.mod' -printf "%h\n")