---
Name: auth
CapsName: Auth

di_go:
  Imports: ""
  Consts: |-
    cliArgID = "auth_id"
    cliArgSecret = "auth_secret"
    cliArgPublicKey = "auth_public_key"
    cliArgPrivateKey = "auth_private_key"
    cliArgNamespace = "auth_namespace"

  ProvideFlags:
    Plugin:
      Usage: "Auth for role based access control, e.g. service"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgID)),
        cli.Usage("Account ID used for client authentication"),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgID)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgSecret)),
        cli.Usage("Account secret used for client authentication"),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgSecret)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgPublicKey)),
        cli.Usage("Public key for JWT auth (base64 encoded PEM)"),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgPublicKey)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgPrivateKey)),
        cli.Usage("Private key for JWT auth (base64 encoded PEM)"),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgPrivateKey)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgNamespace)),
        cli.Usage("Namespace for the services auth account"),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgNamespace)),
      ); err != nil {
        return DiFlags{}, err
      }

  ProvideConfig:
    Body: |-
      f, ok := c.Get(cliArgID)
      f2, ok2 := c.Get(cliArgSecret)
      if ok && ok2 {
        if len(cli.FlagValue(f, defConfig.Auth.ID)) > 0 && len(cli.FlagValue(f2, defConfig.Auth.Secret)) > 0 {
          defConfig.Auth.ID = cli.FlagValue(f, "")
          defConfig.Auth.Secret = cli.FlagValue(f2, "")
        }
      }
      f, ok = c.Get(cliArgPublicKey)
      f2, ok2 = c.Get(cliArgPrivateKey)
      if ok && ok2 {
        if len(cli.FlagValue(f, defConfig.Auth.PublicKey)) > 0 && len(cli.FlagValue(f2, defConfig.Auth.PrivateKey)) > 0 {
          defConfig.Auth.PublicKey = cli.FlagValue(f, "")
          defConfig.Auth.PrivateKey = cli.FlagValue(f2, "")
        }
      }
      if f, ok := c.Get(cliArgNamespace); ok {
        defConfig.Auth.Namespace = cli.FlagValue(f, "")
      }

  Provide:
    Args: ""
    Body: |-
      if len(config.Auth.ID) > 0 && len(config.Auth.Secret) > 0 {
        opts = append(opts, Credentials(
          config.Auth.ID, config.Auth.Secret,
        ))
      }
      opts = append(opts, PublicKey(config.Auth.PublicKey))
      opts = append(opts, PrivateKey(config.Auth.PrivateKey))
      opts = append(opts, Namespace(config.Auth.Namespace))

config_store_go:
  NewConfig:
    Enabled: "false"
    Plugin: ""
    Fields: |-
      ID: "",
      Secret: "",
      PublicKey: "",
      PrivateKey: "",
      Namespace: "",

  Config:
    Fields: |-
      ID string `json:"client,omitempty" yaml:"ID,omitempty"`
      Secret string `json:"secret,omitempty" yaml:"Secret,omitempty"`
      PublicKey string `json:"public_key,omitempty" yaml:"PublicKey,omitempty"`
      PrivateKey string `json:"private_key,omitempty" yaml:"PrivateKey,omitempty"`
      Namespace string `json:"namespace,omitempty" yaml:"Namespace,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Auth.ID = src.Auth.ID
      d.Auth.Secret = src.Auth.Secret
      d.Auth.PublicKey = src.Auth.PublicKey
      d.Auth.PrivateKey = src.Auth.PrivateKey
      d.Auth.Namespace = src.Auth.Namespace
