---
Name: auth
CapsName: Auth

di_go:
  Imports: ""
  Consts: |-
    cliArgID = "auth_id"
    cliArgSecret = "auth_secret"
    cliArgPublicKey = "auth_public_key"
    cliArgPrivateKey = "auth_private_key"
    cliArgNamespace = "auth_namespace"

  ProvideFlags:
    Plugin:
      Usage: "Auth for role based access control, e.g. service"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgID)),
        cli.Usage("Account ID used for client authentication"),
        cli.Default(config.ID),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgID)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgSecret)),
        cli.Usage("Account secret used for client authentication"),
        cli.Default(config.Secret),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgSecret)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgPublicKey)),
        cli.Usage("Public key for JWT auth (base64 encoded PEM)"),
        cli.Default(config.PublicKey),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgPublicKey)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgPrivateKey)),
        cli.Usage("Private key for JWT auth (base64 encoded PEM)"),
        cli.Default(config.PrivateKey),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgPrivateKey)),
      ); err != nil {
        return DiFlags{}, err
      }

      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgNamespace)),
        cli.Usage("Namespace for the services auth account"),
        cli.Default(config.Namespace),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgNamespace)),
      ); err != nil {
        return DiFlags{}, err
      }

  ProvideConfig:
    Body: |-
      f, ok := c.Get(cli.PrefixName(cliConfig.ArgPrefix, cliArgID))
      f2, ok2 := c.Get(cli.PrefixName(cliConfig.ArgPrefix, cliArgSecret))
      if ok && ok2 {
        if len(cli.FlagValue(f, defConfig.ID)) > 0 && len(cli.FlagValue(f2, defConfig.Secret)) > 0 {
          defConfig.ID = cli.FlagValue(f, "")
          defConfig.Secret = cli.FlagValue(f2, "")
        }
      }
      f, ok = c.Get(cli.PrefixName(cliConfig.ArgPrefix, cliArgPublicKey))
      f2, ok2 = c.Get(cli.PrefixName(cliConfig.ArgPrefix, cliArgPrivateKey))
      if ok && ok2 {
        if len(cli.FlagValue(f, defConfig.PublicKey)) > 0 && len(cli.FlagValue(f2, defConfig.PrivateKey)) > 0 {
          defConfig.PublicKey = cli.FlagValue(f, "")
          defConfig.PrivateKey = cli.FlagValue(f2, "")
        }
      }
      if f, ok := c.Get(cli.PrefixName(cliConfig.ArgPrefix, cliArgNamespace)); ok {
        defConfig.Namespace = cli.FlagValue(f, "")
      }

  Provide:
    Args: ""
    Body: |-
      if len(config.ID) > 0 && len(config.Secret) > 0 {
        opts = append(opts, Credentials(
          config.ID, config.Secret,
        ))
      }
      opts = append(opts, PublicKey(config.PublicKey))
      opts = append(opts, PrivateKey(config.PrivateKey))
      opts = append(opts, Namespace(config.Namespace))

config_store_go:
  Imports: ""
  NewConfig:
    Enabled: "false"
    Plugin: ""
    Fields: |-
      ID: "",
      Secret: "",
      PublicKey: "",
      PrivateKey: "",
      Namespace: "",
    Body: ""

  Config:
    Fields: |-
      ID string `json:"client,omitempty" yaml:"ID,omitempty"`
      Secret string `json:"secret,omitempty" yaml:"Secret,omitempty"`
      PublicKey string `json:"public_key,omitempty" yaml:"PublicKey,omitempty"`
      PrivateKey string `json:"private_key,omitempty" yaml:"PrivateKey,omitempty"`
      Namespace string `json:"namespace,omitempty" yaml:"Namespace,omitempty"`

  ConfigMerge:
    Fields: |-
      d.ID = src.ID
      d.Secret = src.Secret
      d.PublicKey = src.PublicKey
      d.PrivateKey = src.PrivateKey
      d.Namespace = src.Namespace
    Body: ""
