---
Name: cache
CapsName: Cache

di_go:
  Imports: ""
  Consts: ""

  ProvideFlags:
    Plugin:
      Usage: "Cache k/v store"

    Body: ""

  ProvideConfig:
    Body: ""

  Provide:
    Args: ""
    Body: ""

config_store_go:
  Imports: ""
  NewConfig:
    Enabled: "false"
    Plugin: ""
    Fields: ""
    Body: ""

  Config:
    Fields: ""

  ConfigMerge:
    Fields: ""
    Body: ""
