---
Name: registry
CapsName: Registry
PluralCapsName: Registries

di_go:
  Imports: |-
    "strings"
  DiFlags:
    Fields: |-
      Addresses string
  Consts: |-
    cliArgAddresses = "registry_address"

  ProvideFlags:
    Plugin:
      Usage: "Registry for discovery. etcd, mdns"

    Body: |-
      if err := c.Add(
        mCli.Name(mCli.PrefixName(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Usage("Comma-separated list of registry addresses"),
        mCli.Default(strings.Join(config.Registry.Addresses, ",")),
        mCli.EnvVars(mCli.PrefixEnv(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Destination(&result.Addresses),
      ); err != nil {
        return nil, err
      }

  ProvideConfig:
    Body: |-
      defConfig.Registry.Addresses = strings.Split(flags.Addresses, ",")

  Provide:
    Body: |-
      opts := []registry.Option{}
      if len(config.Registry.Addresses) > 0 {
        opts = append(opts, registry.Addrs(config.Registry.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "http"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Registry.Addresses = src.Registry.Addresses
