---
Name: registry
CapsName: Registry

di_go:
  Imports: ""
  Consts: |-
    cliArgAddresses = "registry_address"

  ProvideFlags:
    Plugin:
      Usage: "Registry for discovery. etcd, mdns"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
        cli.Usage("List of registry addresses"),
        cli.Default(config.Registry.Addresses),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
      ); err != nil {
        return DiFlags{}, err
      }

  ProvideConfig:
    Body: |-
      if f, ok := c.Get(cliArgAddresses); ok {
        defConfig.Registry.Addresses = cli.FlagValue(f, []string{})
      }

  Provide:
    Args: ""
    Body: |-
      if len(config.Registry.Addresses) > 0 {
        opts = append(opts, Addrs(config.Registry.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "mdns"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Registry.Addresses = src.Registry.Addresses
