---
Name: registry
CapsName: Registry

di_go:
  Imports: |-
    "strings"
  DiFlags:
    Fields: |-
      Addresses string
  Consts: |-
    cliArgAddresses = "registry_address"

  ProvideFlags:
    Plugin:
      Usage: "Registry for discovery. etcd, mdns"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
        cli.Usage("Comma-separated list of registry addresses"),
        cli.Default(strings.Join(config.Registry.Addresses, ",")),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
        cli.Destination(&result.Addresses),
      ); err != nil {
        return nil, err
      }

  ProvideConfig:
    Body: |-
      defConfig.Registry.Addresses = strings.Split(flags.Addresses, ",")

  Provide:
    Body: |-
      if len(config.Registry.Addresses) > 0 {
        opts = append(opts, Addrs(config.Registry.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "mdns"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Registry.Addresses = src.Registry.Addresses
