---
Name: transport
CapsName: Transport

di_go:
  Imports: |-
    "strings"
  DiFlags:
    Fields: |-
      Addresses string
  Consts: |-
    cliArgAddresses = "transport_address"

  ProvideFlags:
    Plugin:
      Usage: "Transport mechanism used; http"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
        cli.Usage("Comma-separated list of transport addresses"),
        cli.Default(strings.Join(config.Transport.Addresses, ",")),
        cli.EnvVars(cli.PrefixEnv(cliConfig.Cli.ArgPrefix, cliArgAddresses)),
        cli.Destination(&result.Addresses),
      ); err != nil {
        return nil, err
      }

  ProvideConfig:
    Body: |-
      defConfig.Transport.Addresses = strings.Split(flags.Addresses, ",")

  Provide:
    Args: ""
    Body: |-
      if len(config.Transport.Addresses) > 0 {
        opts = append(opts, Addrs(config.Transport.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "http"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Transport.Addresses = src.Transport.Addresses
