---
Name: transport
CapsName: Transport

di_go:
  Imports: ""
  Consts: |-
    cliArgAddresses = "transport_address"

  ProvideFlags:
    Plugin:
      Usage: "Transport mechanism used; http"

    Body: |-
      if err := c.Add(
        cli.Name(cli.PrefixName(cliConfig.ArgPrefix, cliArgAddresses)),
        cli.Usage("List of transport addresses"),
        cli.Default(config.Addresses),
        cli.EnvVars(cli.PrefixEnv(cliConfig.ArgPrefix, cliArgAddresses)),
      ); err != nil {
        return DiFlags{}, err
      }

  ProvideConfig:
    Body: |-
      if f, ok := c.Get(cliArgAddresses); ok {
        defConfig.Addresses = cli.FlagValue(f, []string{})
      }
  Provide:
    Args: ""
    Body: |-
      if len(config.Addresses) > 0 {
        opts = append(opts, Addrs(config.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "http"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Addresses = src.Addresses
