---
Name: transport
CapsName: Transport
PluralCapsName: Transports

di_go:
  Imports: |-
    "strings"
  DiFlags:
    Fields: |-
      Addresses string
  Consts: |-
    cliArgAddresses = "transport_address"

  ProvideFlags:
    Plugin:
      Usage: "Transport mechanism used; http"

    Body: |-
      if err := c.Add(
        mCli.Name(mCli.PrefixName(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Usage("Comma-separated list of transport addresses"),
        mCli.Default(strings.Join(config.Transport.Addresses, ",")),
        mCli.EnvVars(mCli.PrefixEnv(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Destination(&result.Addresses),
      ); err != nil {
        return nil, err
      }

  ProvideConfig:
    Body: |-
      defConfig.Transport.Addresses = strings.Split(flags.Addresses, ",")

  Provide:
    Body: |-
      opts := []transport.Option{}
      if len(config.Transport.Addresses) > 0 {
        opts = append(opts, transport.Addrs(config.Transport.Addresses...))
      }

config_store_go:
  NewConfig:
    Enabled: "true"
    Plugin: "http"
    Fields: |-
      Addresses: []string{},

  Config:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`

  ConfigMerge:
    Fields: |-
      d.Transport.Addresses = src.Transport.Addresses
