---
Name: registry
CapsName: Registry
PluralCapsName: Registries

di_go:
  DiFlags:
    Fields: ""
  Consts: ""

  ProvideFlags:
    Plugin:
      Usage: "Registry for discovery. etcd, mdns"

    Body: ""

  ProvideDiConfig:
    Body: ""

  Provide:
    Body: |-
      opts := []registry.Option{}
      if len(config.Addresses) > 0 {
        opts = append(opts, registry.Addrs(config.Addresses...))
      }

config_store_go:
  NewConfigStore:
    Enabled: "true"
    Plugin: "http"
    Fields: ""

  ConfigStore:
    Fields: ""

  ConfigStoreMerge:
    Fields: ""