---
Name: store
CapsName: Store
PluralCapsName: Stores

di_go:
  Imports: |-
    "strings"
  DiFlags:
    Fields: |-
      Addresses string
      Database  string
      Table     string

  Consts: |-
    cliArgAddresses = "store_address"
    cliArgDatabase  = "store_database"
    cliArgTable     = "store_table"

  ProvideFlags:
    Plugin:
      Usage: "Store for pub/sub. http, nats, rabbitmq"

    Body: |-
      if err := c.Add(
        mCli.Name(mCli.PrefixName(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Usage("Comma-separated list of store addresses"),
        mCli.Default(strings.Join(config.Addresses, ",")),
        mCli.EnvVars(mCli.PrefixEnv(cliConfig.ArgPrefix, cliArgAddresses)),
        mCli.Destination(&result.Addresses),
      ); err != nil {
        return nil, err
      }

      if err := c.Add(
        mCli.Name(mCli.PrefixName(cliConfig.ArgPrefix, cliArgDatabase)),
        mCli.Usage("Database option for the underlying store"),
        mCli.Default(config.Database),
        mCli.EnvVars(mCli.PrefixEnv(cliConfig.ArgPrefix, cliArgDatabase)),
        mCli.Destination(&result.Database),
      ); err != nil {
        return nil, err
      }

      if err := c.Add(
        mCli.Name(mCli.PrefixName(cliConfig.ArgPrefix, cliArgTable)),
        mCli.Usage("Table option for the underlying store"),
        mCli.Default(config.Table),
        mCli.EnvVars(mCli.PrefixEnv(cliConfig.ArgPrefix, cliArgTable)),
        mCli.Destination(&result.Table),
      ); err != nil {
        return nil, err
      }

  ProvideDiConfig:
    Body: |-
      defCfg.Addresses = strings.Split(diFlags.Addresses, ",")
      defCfg.Database = diFlags.Database
      defCfg.Table = diFlags.Table

  Provide:
    Body: |-
      opts := []store.Option{}
      if len(config.Addresses) > 0 {
        opts = append(opts, store.Nodes(config.Addresses...))
      }
      if len(config.Database) > 0 {
        opts = append(opts, store.Database(config.Database))
      }
      if len(config.Table) > 0 {
        opts = append(opts, store.Table(config.Table))
      }

config_store_go:
  NewConfigStore:
    Enabled: "false"
    Plugin: ""
    Fields: |-
      Addresses: []string{},
      Database:  "",
      Table:     "",

  ConfigStore:
    Fields: |-
      Addresses []string `json:"addresses,omitempty" yaml:"Addresses,omitempty"`
      Database  string   `json:"database,omitempty" yaml:"Database,omitempty"`
      Table     string   `json:"table,omitempty" yaml:"Table,omitempty"`

  ConfigStoreMerge:
    Fields: |-
      d.Addresses = src.Addresses
      d.Database = src.Database
      d.Table = src.Table
