---
Name: transport
CapsName: Transport
PluralCapsName: Transports

di_go:
  DiFlags:
    Fields: ""
  Consts: ""

  ProvideFlags:
    Plugin:
      Usage: "Transport mechanism used; http"

    Body: ""

  ProvideDiConfig:
    Body: ""

  Provide:
    Body: |-
      opts := []transport.Option{}
      if len(config.Addresses) > 0 {
        opts = append(opts, transport.Addrs(config.Addresses...))
      }

config_store_go:
  NewConfigStore:
    Enabled: "true"
    Plugin: "http"
    Fields: ""

  ConfigStore:
    Fields: ""

  ConfigStoreMerge:
    Fields: ""
